---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.0.1
  values:
    installCRDs: true
    prometheus.serviceMonitor.enabled: true
